apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
  namespace: webapps
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGJmd2t1M2Nk
  CLOUDINARY_KEY: Mzk2OTg1NjQzMjg5Mzcz
  CLOUDINARY_SECRET: c1VFdFJuLS1XZlJycEVlNVZJX2phaWRqRDRv
  DB_URL: bW9uZ29kYitzcnY6Ly9hd3NkZXY4ODk5X2RiX3VzZXI6N0d3cmdGVFNZSE9LTEtDenoQGNsdXN0ZXIwLmtxYzRncmwubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
  MAPBOX_TOKEN: ZHVtbXktbWFwYm94LXRva2Vu
